import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/url_strategy.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'models/user_model.dart';
import 'services/json_storage_service.dart';
import 'screens/auth_screen.dart';
import 'screens/dashboard_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  usePathUrlStrategy();
  
  // Initialize Firebase Cloud Service
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Information Sciences Mixer 2026',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const RootSessionWrapper(),
    );
  }
}

class RootSessionWrapper extends StatefulWidget {
  const RootSessionWrapper({super.key});

  @override
  State<RootSessionWrapper> createState() => _RootSessionWrapperState();
}

class _RootSessionWrapperState extends State<RootSessionWrapper> {
  bool _isLoading = true;
  User? _currentUser;

  @override
  void initState() {
    super.initState();
    _checkExistingSession();
  }

  Future<void> _checkExistingSession() async {
    final user = await JsonStorageService.getActiveSessionUser();
    setState(() {
      _currentUser = user;
      _isLoading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Scaffold(
        body: Center(child: CircularProgressIndicator()),
      );
    }

    if (_currentUser != null) {
      return GameDashboardScreen(
        user: _currentUser!,
        onLogout: () => setState(() => _currentUser = null),
      );
    }

    return AuthScreen(
      onLoginSuccess: (user) => setState(() => _currentUser = user),
    );
  }
}